#!/usr/bin/env bash
# fix-steam-launcher.sh — make the Steam desktop icon work on this ARM64 box. No sudo.
#
# WHY THIS EXISTS
#   Launching Steam from the GNOME icon does nothing on this machine. The cause is in Valve's
#   own launcher, /usr/lib/steam/bin_steam.sh (which /usr/bin/steam symlinks to):
#
#       ARCH=$(arch)
#       if [[ "$ARCH" == "aarch64" ]]; then
#         FEXBash $0 "$@"          # <-- passes a SCRIPT PATH to FEXBash
#
#   Handing FEXBash a script path instead of `-c` is a known failure mode on this rig: the script
#   is then parsed by dash, which cannot do `[[` (line 16) or `function` (line 39), so it dies with
#       /usr/bin/steam: 16: [[: not found
#       /usr/bin/steam: 39: Syntax error: "(" unexpected
#   and Steam never starts. The working invocation is `FEXBash -c steam`.
#
#   Fixed with a USER-LEVEL override rather than by editing the root-owned script, because:
#     - no sudo (which needs a password here and cannot run from the agent shell), and
#     - an apt update of the steam package would overwrite bin_steam.sh again, silently.
#   ~/.local/share/applications takes precedence over /usr/share/applications, so the icon,
#   its right-click actions, and steam:// URL handling all pick this up.
#
#   The wrapper is NOT named `steam`: ~/.local/bin is on PATH and is inherited into the FEX
#   environment, so a wrapper called `steam` running `FEXBash -c steam` would re-enter itself
#   forever. It is named steam-fex and invokes /usr/bin/steam by ABSOLUTE path inside FEX.
#
#   DISPLAY is resolved from the running Xwayland (this is a Wayland session; Xwayland is :0 here,
#   not :1 as an earlier note in this project claimed). It is only set if not already present.
#
# Usage:  tools/fix-steam-launcher.sh          # install
#         tools/fix-steam-launcher.sh --undo   # remove the override
#
set -uo pipefail
BIN="$HOME/.local/bin/steam-fex"
DESKTOP="$HOME/.local/share/applications/steam.desktop"
SYS="/usr/share/applications/steam.desktop"

if [ "${1:-}" = "--undo" ]; then
  rm -f "$BIN" "$DESKTOP" && echo "removed $BIN and $DESKTOP"
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$HOME/.local/share/applications" 2>/dev/null
  echo "system launcher restored (icon will be broken again until this is re-run)"; exit 0
fi

[ -f "$SYS" ] || { echo "missing $SYS — is Steam installed?"; exit 1; }
command -v FEXBash >/dev/null 2>&1 || { echo "FEXBash not on PATH"; exit 1; }

mkdir -p "$(dirname "$BIN")" "$(dirname "$DESKTOP")"
cat > "$BIN" <<'EOF'
#!/usr/bin/env bash
# Launch Steam under FEX with the -c form. Generated by tools/fix-steam-launcher.sh.
# Valve's bin_steam.sh does `FEXBash $0 "$@"`, which dash then fails to parse; `-c` is required.
set -u
if [ -z "${DISPLAY:-}" ]; then
  d=$(ps -eo args 2>/dev/null | grep -m1 '[X]wayland' | grep -oE ' :[0-9]+' | tr -d ' ')
  export DISPLAY="${d:-:0}"
fi
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
# Absolute path: ~/.local/bin is inherited into FEX, so a bare `steam` could re-enter this wrapper.
cmd="/usr/bin/steam"
for a in "$@"; do cmd="$cmd $(printf '%q' "$a")"; done
exec FEXBash -c "$cmd"
EOF
chmod +x "$BIN"

# Copy the system entry verbatim, then repoint every Exec= at the wrapper. Keeping the original
# file wholesale preserves all the translated Name/Comment strings and the desktop actions.
sed -e "s|^Exec=/usr/bin/steam |Exec=$BIN |" -e "s|^Exec=steam |Exec=$BIN |" "$SYS" > "$DESKTOP"
chmod 644 "$DESKTOP"
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$HOME/.local/share/applications" 2>/dev/null

echo "installed:"
echo "  wrapper : $BIN"
echo "  desktop : $DESKTOP"
echo
echo "Exec lines now:"
grep -c "^Exec=$BIN" "$DESKTOP" | sed 's/^/  rewritten: /'
grep -c '^Exec=' "$DESKTOP" | sed 's/^/  total:     /'
left=$(grep '^Exec=' "$DESKTOP" | grep -vc "^Exec=$BIN")
[ "$left" -eq 0 ] && echo "  all Exec lines point at the wrapper" || { echo "  !! $left NOT rewritten:"; grep '^Exec=' "$DESKTOP" | grep -v "^Exec=$BIN" | sed 's/^/    /'; }
