#!/usr/bin/env bash
# make-launcher-shim.sh — replace a game's launcher with a ~10 KB stub that just
# starts the real executable and waits for it.
#
# WHY THIS EXISTS
#   Over and over on this rig the ENGINE is fine and the LAUNCHER is the blocker:
#     * Cyberpunk 2077's REDprelauncher (Qt + CEF) failed to hand off ~10 times in
#       a row on 2026-09-07. CEF under FEX is the least reliable thing here. A
#       hand-written 10 KB shim fixed it outright.
#     * Ubisoft Connect crashes with an unrecoverable error and blocks SEVEN Far
#       Cry titles, yet launching fc3_blooddragon_d3d11.exe directly renders fine
#       -- the Dunia engine works, the launcher does not.
#   Doing this by hand meant writing, cross-compiling and installing a PE each
#   time. This makes it one command, reversibly.
#
#   Steam insists on running the launcher it has on record, and editing launch
#   options requires Steam closed. Replacing the FILE sidesteps both.
#
#   The shim must WAIT on the child: Steam tracks the process it started, so
#   exiting immediately makes Steam believe the game closed (and can make it kill
#   the real game). That single detail is most of why this is a tool.
#
# Usage:
#   tools/make-launcher-shim.sh <launcher.exe> <target-relative-to-launcher-dir>
#   tools/make-launcher-shim.sh --undo <launcher.exe>
#
# Example:
#   tools/make-launcher-shim.sh \
#     "$STEAM/steamapps/common/Cyberpunk 2077/REDprelauncher.exe" 'bin\x64\Cyberpunk2077.exe'
#
# The original is backed up beside it as <name>.orig and never overwritten, so
# --undo always has something to restore and re-running is safe.
set -uo pipefail
TC="$HOME/dgx-gaming-work/toolchain/root/usr/bin"

if [ "${1:-}" = "--undo" ]; then
  L="${2:-}"; [ -n "$L" ] || { echo "usage: $0 --undo <launcher.exe>"; exit 2; }
  [ -f "$L.orig" ] || { echo "!! no backup at $L.orig — nothing to restore"; exit 1; }
  mv -f "$L.orig" "$L" && echo "restored $L"; exit 0
fi

L="${1:-}"; T="${2:-}"
[ -n "$L" ] && [ -n "$T" ] || { sed -n '/^# Usage:/,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }
[ -f "$L" ] || { echo "!! no such launcher: $L"; exit 1; }

DIR=$(dirname "$L")
# Sanity: the target must actually exist, or we install a shim that cannot work.
TCHK=$(printf '%s' "$T" | tr '\\' '/')
[ -f "$DIR/$TCHK" ] || { echo "!! target does not exist: $DIR/$TCHK"; echo "   (path is relative to the launcher's own directory, backslashes ok)"; exit 1; }

# Match the launcher's architecture — a 64-bit shim in place of a 32-bit
# launcher will simply refuse to start, with no useful error.
case "$(file -b "$L")" in
  *x86-64*|*PE32+*) CC="$TC/x86_64-w64-mingw32-gcc-win32"; BITS=64 ;;
  *80386*|*PE32*)   CC="$TC/i686-w64-mingw32-gcc-win32";   BITS=32 ;;
  *) echo "!! $L is not a Windows PE"; exit 1 ;;
esac
[ -x "$CC" ] || { echo "!! need $BITS-bit mingw. Run: MINGW_ARCH=$([ $BITS = 32 ] && echo i686 || echo x86-64) tools/setup-mingw.sh"; exit 1; }

WORK=$(mktemp -d "${CLAUDE_JOB_DIR:-/tmp}/shim.XXXXXX"); trap 'rm -rf "$WORK"' EXIT
ESC=$(printf '%s' "$T" | sed 's/\\/\\\\/g')

cat > "$WORK/shim.c" <<CEOF
/* Generated by tools/make-launcher-shim.sh — stands in for a game launcher.
 * Target: $T
 * It resolves the target relative to its OWN location, forwards its arguments,
 * and WAITS -- Steam tracks this process, so returning early looks like the game
 * exiting. */
#include <windows.h>
#include <stdio.h>     /* _snwprintf: implicit declaration is a real varargs
                        * hazard with wide strings, not a cosmetic warning */
#include <wchar.h>

int main(void) {
    wchar_t self[MAX_PATH];
    if (!GetModuleFileNameW(NULL, self, MAX_PATH)) return 1;
    wchar_t *slash = wcsrchr(self, L'\\\\');
    if (slash) *slash = 0;

    wchar_t exe[MAX_PATH * 2], dir[MAX_PATH * 2];
    _snwprintf(exe, MAX_PATH * 2, L"%s\\\\%s", self, L"$ESC");
    wcscpy(dir, exe);
    slash = wcsrchr(dir, L'\\\\');
    if (slash) *slash = 0;

    const wchar_t *a = GetCommandLineW();
    if (*a == L'"') { a++; while (*a && *a != L'"') a++; if (*a) a++; }
    else { while (*a && *a != L' ') a++; }
    while (*a == L' ') a++;

    static wchar_t cmd[32768];
    _snwprintf(cmd, 32768, L"\\"%s\\" %s", exe, a);

    STARTUPINFOW si; PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof si); si.cb = sizeof si;
    ZeroMemory(&pi, sizeof pi);
    if (!CreateProcessW(exe, cmd, NULL, NULL, FALSE, 0, NULL, dir, &si, &pi)) {
        wchar_t m[MAX_PATH * 2 + 128];
        _snwprintf(m, MAX_PATH * 2 + 128, L"launcher shim: could not start\\n%s\\n(error %lu)",
                   exe, GetLastError());
        MessageBoxW(NULL, m, L"launcher shim", MB_ICONERROR | MB_OK);
        return 1;
    }
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD rc = 0; GetExitCodeProcess(pi.hProcess, &rc);
    CloseHandle(pi.hThread); CloseHandle(pi.hProcess);
    return (int)rc;
}
CEOF

"$CC" -O2 -o "$WORK/shim.exe" "$WORK/shim.c" -lgdi32 2>&1 | head -20
[ -f "$WORK/shim.exe" ] || { echo "!! build failed"; exit 1; }

[ -f "$L.orig" ] || cp -a "$L" "$L.orig"
cp -f "$WORK/shim.exe" "$L"
echo "shim installed ($BITS-bit, $(stat -c%s "$L") bytes)"
echo "  replaced : $L"
echo "  backup   : $L.orig"
echo "  runs     : $DIR/$TCHK"
echo "  undo     : tools/make-launcher-shim.sh --undo '$L'"
